### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shuban-789** [SAAK-APCSP/Bluejay-Backend#1]
- [x] Create login database 
- [x] Orchestrate page changes for site tree
- [x] Use way to store post
